# Generated by Django 4.2.7 on 2024-01-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_fname', models.CharField(max_length=255)),
                ('signup_lname', models.CharField(max_length=255)),
                ('signup_email', models.CharField(max_length=255)),
                ('signup_product', models.CharField(max_length=255)),
                ('signup_number', models.CharField(max_length=255)),
            ],
        ),
    ]
